package langintel

// pyKB returns the embedded Python knowledge base.
func pyKB() *Registry {
	return &Registry{
		Practices: []Practice{
			{
				ID:      "py-type-hints",
				Summary: "Use type hints — Python 3.10+ union syntax preferred",
				Body: `Annotate function signatures and class attributes with type hints. Python 3.10+ supports | for unions (def foo(x: int | str) -> bool | None). Use mypy or pyright for static checking. Type hints make code self-documenting and catch type-related bugs at write time.`,
				Langs: []string{"python"},
				Kinds: []string{"function_def", "async_function_def", "parameter"},
				Tags:  []string{"type-safety", "style"},
			},
			{
				ID:      "py-context-manager",
				Summary: "Use with statements for resource cleanup",
				Body: `Always use with open(path) as f: for file I/O, and contextlib.contextmanager for custom context managers. This guarantees __exit__ runs even when exceptions occur, preventing resource leaks.`,
				Langs: []string{"python"},
				Kinds: []string{"with_statement", "async_with_statement"},
				Tags:  []string{"resource-management"},
			},
			{
				ID:      "py-exception-hierarchy",
				Summary: "Catch specific exceptions, not bare except:",
				Body: `Bare except: catches everything including KeyboardInterrupt and SystemExit. Catch the most specific exception type possible: except ValueError as e: not except Exception:. For truly recoverable errors, log and handle gracefully rather than silently swallowing.`,
				Langs: []string{"python"},
				Kinds: []string{"except_handler"},
				Tags:  []string{"error-handling"},
			},
			{
				ID:      "py-dataclass",
				Summary: "Use dataclasses or attrs for structured data containers",
				Body: `@dataclass from dataclasses produces __init__, __repr__, __eq__ automatically. Prefer over hand-rolled __init__ for plain data carriers. For more features (validators, serialization), use attrs or Pydantic.`,
				Langs: []string{"python"},
				Kinds: []string{"class_def", "decorator"},
				Tags:  []string{"design", "style"},
			},
			{
				ID:      "py-f-string",
				Summary: "Prefer f-strings for string formatting",
				Body: `f-strings are the most readable and fastest formatting option in Python 3.6+. Use :.2f for floats, :04d for zero-padded ints. Avoid %-formatting and .format() for new code.`,
				Langs: []string{"python"},
				Kinds: []string{"joined_string"},
				Tags:  []string{"style", "performance"},
			},
			{
				ID:      "py-comprehension",
				Summary: "Use list/dict/set comprehensions for simple transformations",
				Body: `[x for x in items if x > 0] is idiomatic and faster than building a list in a loop. Keep comprehensions short — split into multiple comprehensions or a regular loop for complex logic.`,
				Langs: []string{"python"},
				Kinds: []string{"list_comprehension", "dict_comprehension", "set_comprehension"},
				Tags:  []string{"style", "idiom"},
			},
		},
		BugPatterns: []BugPattern{
			{
				ID:       "pymutable-default",
				Summary:  "Never use a mutable object as a default argument",
				Body:     "Default arguments are evaluated once at function definition time, not at call time. Using [] or {} as a default leads to shared state across calls: def foo(items=[]) accumulates items across invocations. Use None and create the mutable inside the function.",
				Langs:    []string{"python"},
				Kinds:    []string{"argument", "function_def"},
				Severity: "error",
				Fix:      "Use def foo(items=None): if items is None: items = []",
				CWE:      "CWE-710",
			},
			{
				ID:       "py-shadowed",
				Summary:  "Local variable shadows an enclosing scope name — verify intent",
				Body:     "Assignment to a variable inside a function makes it local. Reading before assignment (if it exists in an outer scope) raises UnboundLocalError. Either rename the local or use 'nonlocal' / 'global' to explicitly declare intent.",
				Langs:    []string{"python"},
				Kinds:    []string{"assignment", "annassign"},
				Severity: "warning",
				CWE:      "CWE-710",
			},
			{
				ID:       "py-name-attr",
				Summary:  "Use hasattr/getattr safely, not try/except AttributeError",
				Body:     "Catching AttributeError to check attribute existence is error-prone (AttributeError can be raised from within the attribute). Use hasattr(obj, 'attr') or getattr(obj, 'attr', default) instead.",
				Langs:    []string{"python"},
				Kinds:    []string{"try_statement"},
				Severity: "warning",
				Fix:      "Use getattr(obj, 'attr', None) or hasattr(obj, 'attr')",
			},
			{
				ID:       "py-regex-capture",
				Summary:  "Always use raw strings (r'...') for regex patterns",
				Body:     "A regular string '\\d' in a regex means \\ followed by d (which is just 'd'). Use r'\\d' to match digits. This is a common source of silent bugs where the pattern looks correct but matches nothing.",
				Langs:    []string{"python"},
				Kinds:    []string{"string"},
				Severity: "warning",
			},
			{
				ID:       "py-gil",
				Summary:  "CPU-bound work in Python needs multiprocessing, not threading",
				Body:     "Python's GIL prevents true parallelism for CPU-bound tasks in threads. Use multiprocessing.Pool or concurrent.futures.ProcessPoolExecutor for CPU-bound work. threading is still useful for I/O-bound concurrency.",
				Langs:    []string{"python"},
				Kinds:    []string{"import_statement", "function_def"},
				Severity: "info",
				CWE:      "CWE-330", // Use of Insufficiently Random Values (overlapping concern)
			},
			{
				ID:       "py-walrus",
				Summary:  "Walrus operator (:=) in comprehension condition — ensure correct scope",
				Body:     "The walrus operator := assigns and returns a value. In a list comprehension with a filter, the assignment is in the outer scope — verify this is intentional and not a bug from refactoring a regular loop.",
				Langs:    []string{"python"},
				Kinds:    []string{"named_expr"},
				Severity: "info",
			},
			{
				ID:       "py-nested-all",
				Summary:  "all() with a generator — always pass an expression, not a comparison chain",
				Body:     "all(x > 0 for x in items) is correct. all(x > 0 and y > 0 for x, y in pairs) is wrong — the 'and' makes it a single boolean expression, not a generator. Use all(x > 0 and y > 0 for x, y in pairs) correctly by comparing in the generator body.",
				Langs:    []string{"python"},
				Kinds:    []string{"call_expression"},
				Severity: "warning",
			},
		},
		SecurityRules: []SecurityRule{
			{
				ID:       "py-pickle",
				Summary:  "Never unpickle untrusted data — use json or marshaling of primitives",
				Body:     "pickle.loads(data) from an untrusted source is arbitrary code execution. An attacker can craft a pickle payload that runs arbitrary Python when deserialized. Use json.loads for untrusted data, or a signed serialization format like marshmallow.",
				Langs:    []string{"python"},
				Kinds:    []string{"call_expression"},
				CWE:      "CWE-502",
				OWASP:    "A08:2021",
				Severity: "critical",
			},
			{
				ID:       "py-sql-injection",
				Summary:  "Use parameterized queries — never f-string or % formatting in SQL",
				Body:     "String interpolation into SQL is SQL injection. Use cursor.execute('SELECT * FROM users WHERE id = %s', (user_id,)) with a tuple of parameters. SQLAlchemy and Django ORM generate parameterized queries automatically.",
				Langs:    []string{"python"},
				Kinds:    []string{"call_expression", "joined_string"},
				CWE:      "CWE-89",
				OWASP:    "A03:2021",
				Severity: "critical",
			},
			{
				ID:       "py-command-injection",
				Summary:  "Never pass unsanitized input to subprocess / os.system / eval",
				Body:     "subprocess.run with shell=True and user input is command injection. Use shell=False and pass arguments as a list: subprocess.run(['ls', path]) without any shell interpretation. Never use os.system or exec with user input.",
				Langs:    []string{"python"},
				Kinds:    []string{"call_expression"},
				CWE:      "CWE-78",
				OWASP:    "A03:2021",
				Severity: "critical",
			},
			{
				ID:       "py-yaml-unsafe",
				Summary:  "Never use yaml.load with Loader=yaml.FullLoader on untrusted input",
				Body:     "yaml.load(input) without a safe Loader can execute arbitrary Python code from the YAML payload. Use yaml.safe_load for untrusted input. If you need custom constructors, define an explicit SafeLoader subclass.",
				Langs:    []string{"python"},
				Kinds:    []string{"call_expression"},
				CWE:      "CWE-502",
				OWASP:    "A08:2021",
				Severity: "critical",
			},
			{
				ID:       "py-hardcoded-secret",
				Summary:  "Do not embed secrets or API keys in source code",
				Body:     "Hardcoded credentials in Python source are visible to anyone with access to the code. Use environment variables: os.environ.get('API_KEY') or python-dotenv to load from .env files excluded from version control.",
				Langs:    []string{"python"},
				Kinds:    []string{"assignment", "import_statement"},
				CWE:      "CWE-798",
				Severity: "critical",
			},
			{
				ID:       "py-path-traversal",
				Summary:  "Validate path inputs to prevent directory traversal",
				Body:     "User-supplied paths like ../../etc/passwd can escape the intended directory. Use os.path.realpath to resolve symlinks and confirm the path stays within the allowed root, or use pathlib.Path with strict=True (Python 3.11+).",
				Langs:    []string{"python"},
				Kinds:    []string{"call_expression", "binary_op"},
				CWE:      "CWE-22",
				OWASP:    "A01:2021",
				Severity: "high",
			},
		},
		Idioms: []Idiom{
			{ID: "py-snake-case", Lang: "python", Rule: "Use snake_case for functions, variables, and module names",
				Detail: "Python convention (PEP 8): function names and variable names use lowercase_with_underscores. Class names use PascalCase.",
				Kinds: []string{"function_def", "variable_name"}},
			{ID: "py-guard", Lang: "python", Rule: "Use if __name__ == '__main__': guard for entry points",
				Detail: "The guard ensures code only runs when the module is executed directly, not when imported. Always wrap main() calls in this guard in scripts.",
				Kinds: []string{"if_statement"}},
			{ID: "py-typing-guard", Lang: "python", Rule: "Use TYPE_CHECKING guard to avoid circular imports",
				Detail: "from typing import TYPE_CHECKING; if TYPE_CHECKING: import SomeType avoids runtime circular import issues while still providing type information to static checkers.",
				Kinds: []string{"import_statement"}},
			{ID: "py-early-return", Lang: "python", Rule: "Prefer early return (fail fast) over deeply nested conditionals",
				Detail: "Replace deeply nested if/else with early returns at the top of a function. This reduces cognitive load and makes the happy path clear. After all guards return, the main logic executes.",
				Kinds: []string{"if_statement", "function_def"}},
		},
	}
}
