package langintel

// rustKB returns the embedded Rust knowledge base.
func rustKB() *Registry {
	return &Registry{
		Practices: []Practice{
			{
				ID:      "rust-ownership",
				Summary: "Embrace the ownership model — no garbage collector, no data races",
				Body: `Rust's ownership rules: each value has a single owner. When the owner goes out of scope, the value is dropped. Use references (&T) for read-only access, &mut T for exclusive write access. The borrow checker enforces these rules at compile time.`,
				Langs: []string{"rust"},
				Kinds: []string{"let_statement", "let_declaration", "reference_expression"},
				Tags:  []string{"ownership", "memory"},
			},
			{
				ID:      "rust-derive",
				Summary: "Derive common traits rather than implementing manually",
				Body: `Use #[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Hash)] on structs and enums to get standard trait implementations automatically. Only implement traits manually when the derived behavior is incorrect or when required by the trait (e.g. Serialize/Deserialize from serde).`,
				Langs: []string{"rust"},
				Kinds: []string{"struct", "enum"},
				Tags:  []string{"idiom", "traits"},
			},
			{
				ID:      "rust-error",
				Summary: "Use the ? operator and thiserror/anyhow for error handling",
				Body: `The ? operator propagates errors concisely: fn read() -> Result<String, io::Error> { let s = std::fs::read_to_string("file")?; Ok(s) }. Use thiserror for library code (defines your error type) and anyhow for application code (dynamic error context).`,
				Langs: []string{"rust"},
				Kinds: []string{"function_item", "macro_invocation"},
				Tags:  []string{"error-handling"},
			},
			{
				ID:      "rust-iterators",
				Summary: "Prefer iterators over index loops",
				Body: `Rust iterators are zero-cost abstractions — the optimizer eliminates iterator overhead. Prefer .iter().filter().map().collect() over manual index loops. Use .enumerate() when you need the index, .zip() for parallel iteration, .fold() for accumulations.`,
				Langs: []string{"rust"},
				Kinds: []string{"for_expression", "loop_expression"},
				Tags:  []string{"idiom", "performance"},
			},
			{
				ID:      "rust-clippy",
				Summary: "Run clippy — it catches style and correctness issues the compiler misses",
				Body: `clippy is the official Rust linter. Run cargo clippy regularly. It enforces idiomatic Rust, catches common mistakes (like .clone() on Copy types), and provides suggestions. Add #[allow(clippy::some_lint)] with a comment when you intentionally deviate.`,
				Langs: []string{"rust"},
				Kinds: []string{"source_file", "attribute_item"},
				Tags:  []string{"tooling", "style"},
			},
			{
				ID:      "rust-match-exhaustive",
				Summary: "Always handle all variants in match expressions",
				Body: `Rust match expressions must be exhaustive — the compiler ensures every possible value is matched. Use _ => () for the fallback case, or #[non_exhaustive] on enums from external crates to require a wildcard. Adding a new enum variant without updating all match arms is a compile error.`,
				Langs: []string{"rust"},
				Kinds: []string{"match_expression"},
				Tags:  []string{"type-safety", "idiom"},
			},
		},
		BugPatterns: []BugPattern{
			{
				ID:       "rust-borrow-mutable",
				Summary:  "Cannot borrow as mutable more than once — use RefCell or redesign",
				Body:     "Multiple &mut references to the same data at the same time are not allowed in safe Rust. If you need interior mutability, use std::cell::RefCell (runtime checked) or atomic types from std::sync, or wrap in Arc<Mutex<T>> for multi-threaded access.",
				Langs:    []string{"rust"},
				Kinds:    []string{"reference_expression", "borrow_expression"},
				Severity: "error",
				CWE:      "CWE-675", // Operations on Resource in Wrong Phase of Lifetime
			},
			{
				ID:       "rust-lifetime-param",
				Summary:  "Lifetime parameter not used — this may indicate a bug or unnecessary annotation",
				Body:     "A lifetime parameter on a struct or function that only appears once (and not in the return type) is usually a mistake. It should either be used to relate input and output lifetimes, or removed if not needed.",
				Langs:    []string{"rust"},
				Kinds:    []string{"type_alias_declaration", "function_item", "struct"},
				Severity: "warning",
			},
			{
				ID:       "rust-index-out-of-bounds",
				Summary:  "Slice index access panics if out of bounds — use .get() for safe access",
				Body:     "Using v[i] where i >= v.len() panics at runtime. Use v.get(i) which returns Option<&T>, or v.get_mut(i) for mutable access. Prefer iterators over index loops to avoid off-by-one errors entirely.",
				Langs:    []string{"rust"},
				Kinds:    []string{"index_expression"},
				Severity: "error",
				CWE:      "CWE-125",
			},
			{
				ID:       "rust-unwrap",
				Summary:  "unwrap() panics on None/Err — use ? or expect with a message",
				Body:     "unwrap() on a Result::Err or Option::None causes a panic. In tests, unwrap() is acceptable for clearly-valid data. In library code, use ? for propagation or .expect(\"descriptive message\") with a message that helps debugging.",
				Langs:    []string{"rust"},
				Kinds:    []string{"method_invocation", "macro_invocation"},
				Severity: "warning",
			},
			{
				ID:       "rust-dead-code",
				Summary:  "Dead code warning — unused function or field",
				Body:     "Rust emits warnings for code that is never used. Either remove it, make it pub, mark it with #[allow(dead_code)] with a comment explaining why it must stay, or use it.",
				Langs:    []string{"rust"},
				Kinds:    []string{"function_item", "struct_field", "struct"},
				Severity: "info",
			},
			{
				ID:       "rust-mutex-poison",
				Summary:  "MutexGuard is dropped at end of scope — release the lock explicitly",
				Body:     "MutexGuard<T> automatically releases the lock when dropped (end of scope). Holding it across await points in async Rust can deadlock if the guard is held across a .await. Release locks before await, or use tokio::sync::Mutex for async contexts.",
				Langs:    []string{"rust"},
				Kinds:    []string{"loop_expression", "async_block"},
				Severity: "warning",
			},
		},
		SecurityRules: []SecurityRule{
			{
				ID:       "rust-command-injection",
				Summary:  "Never pass unsanitized input to Command",
				Body:     "std::process::Command with shell=true or with user-controlled args allows command injection. Use Command::new without shell=true and pass args as a slice. For shell features (redirection, pipes), validate input against a safelist of allowed values.",
				Langs:    []string{"rust"},
				Kinds:    []string{"macro_invocation", "call_expression"},
				CWE:      "CWE-78",
				OWASP:    "A03:2021",
				Severity: "critical",
			},
			{
				ID:       "rust-hardcoded-secret",
				Summary:  "Do not embed secrets in Rust source",
				Body:     "Hardcoded credentials in Rust source are compiled into the binary and visible in the compiled output. Use environment variables (std::env::var) or a secrets manager. For tests, use std::env::set_var at test setup time.",
				Langs:    []string{"rust"},
				Kinds:    []string{"literal", "assignment_expression"},
				CWE:      "CWE-798",
				Severity: "critical",
			},
			{
				ID:       "rust-unsafe-use",
				Summary:  "unsafe code bypasses Rust's memory safety guarantees",
				Body:     "unsafe allows dereferencing raw pointers, calling unsafe functions, implementing unsafe traits, and accessing mutable statics. Every unsafe block must be reviewed carefully. Document why each unsafe is safe, and keep the unsafe surface area as small as possible.",
				Langs:    []string{"rust"},
				Kinds:    []string{"unsafe_block"},
				CWE:      "CWE-120", // Buffer Copy without Checking Size of Input (overlapping concern)
				Severity: "high",
			},
			{
				ID:       "rust-random-weak",
				Summary:  "Use rand::SeedableRng with crypto-grade entropy for security-sensitive randomness",
				Body:     "The default rand::thread_rng is not cryptographically secure. For secrets, keys, or tokens, use rand::rngs::OsRng or rand::SeedableRng with crypto-seeded state. Never use rand::StdRng for security-sensitive randomness.",
				Langs:    []string{"rust"},
				Kinds:    []string{"function_item", "call_expression"},
				CWE:      "CWE-330",
				Severity: "high",
			},
		},
		Idioms: []Idiom{
			{ID: "rust-snake-case", Lang: "rust", Rule: "Use snake_case for functions, variables, modules; SCREAMING_SNAKE_CASE for constants",
				Detail: "Rust convention (RFC 430): functions and variables are snake_case. Types and traits are PascalCase. Modules are also snake_case. Constants (including static) use SCREAMING_SNAKE_CASE.",
				Kinds: []string{"function_item", "let_declaration", "module", "struct", "trait", "constant_item"}},
			{ID: "rust-struct-update", Lang: "rust", Rule: "Use struct update syntax ..Default::default() for partial initialization",
				Detail: "StructUpdateSyntax ..expr allows setting some fields and copying the rest from another instance: let b = A { field2: 2, ..a }. Note that the base (a) must come last.",
				Kinds: []string{"struct_expression"}},
			{ID: "rust-match-wildcard", Lang: "rust", Rule: "Use _ => arm for wildcard in match — order matters for non-wildcard arms",
				Detail: "In a match expression, arms are evaluated in order. A wildcard (_ =>) must come LAST, after all specific patterns, or it will match everything. For Option<T>, prefer if let Some(x) = opt rather than match for single-case handling.",
				Kinds: []string{"match_expression"}},
			{ID: "rust-dyn-trait", Lang: "rust", Rule: "Use dyn Trait for runtime polymorphism — add the dyn keyword",
				Detail: "dyn Trait is a trait object (vtable-based dispatch). dyn is required since Rust 2018.dyn Box<dyn Trait>, dyn &Trait, &dyn Trait all work. dyn provides runtime polymorphism at the cost of heap allocation and dynamic dispatch.",
				Kinds: []string{"trait_object_type", "type_alias_declaration"}},
		},
	}
}
