package langintel

// tsKB returns the embedded TypeScript/JavaScript knowledge base.
func tsKB() *Registry {
	return &Registry{
		Practices: []Practice{
			{
				ID:      "ts-strict",
				Summary: "Enable strict mode in tsconfig.json",
				Body: `Enable "strict": true in tsconfig.json. It bundles noImplicitAny, noImplicitThis, strictNullChecks, and strictFunctionTypes — catching more bugs at compile time rather than runtime.`,
				Langs: []string{"typescript"},
				Kinds: []string{"tsconfig", "project_file"},
				Tags:  []string{"type-safety"},
			},
			{
				ID:      "ts-no-any",
				Summary: "Avoid any — use unknown or specific types",
				Body: `Replace : any with : unknown when the type is truly unknown. Use type guards or narrowing before operating on unknown values. For dynamic shapes, define an interface or use a discriminated union.`,
				Langs: []string{"typescript"},
				Kinds: []string{"variable_declaration", "parameter"},
				Tags:  []string{"type-safety"},
			},
			{
				ID:      "ts-interface",
				Summary: "Prefer interfaces over type aliases for object shapes",
				Body: `Interfaces are more readable, can be extended and merged, and produce better error messages. Use type for unions, intersections, and mapped types where interfaces cannot express the shape.`,
				Langs: []string{"typescript"},
				Kinds: []string{"interface_declaration", "type_alias"},
				Tags:  []string{"design", "types"},
			},
			{
				ID:      "ts-enum",
				Summary: "Prefer const enums or union types over plain enums",
				Body: `Plain enums generate runtime code and can cause issues with tree-shaking. Use const enum for compile-time constants, or a string union type for exhaustive sets of strings.`,
				Langs: []string{"typescript"},
				Kinds: []string{"enum_declaration"},
				Tags:  []string{"type-safety", "performance"},
			},
			{
				ID:      "ts-dispose",
				Summary: "Clean up subscriptions and timers in Angular/React/Node",
				Body: `Unsubscribe from observables and events in ngOnDestroy, useEffect cleanup, or finally blocks. Undisposed subscriptions cause memory leaks and stale callbacks in long-running apps.`,
				Langs: []string{"typescript"},
				Kinds: []string{"method_declaration", "call_expression"},
				Tags:  []string{"resource-management", "memory"},
			},
			{
				ID:      "ts-async-await",
				Summary: "Prefer async/await over raw Promise chains",
				Body: `async/await produces more readable code than chained .then().catch(). Use Promise.all for parallel independent async operations, not sequential awaits in a loop.`,
				Langs: []string{"typescript", "javascript"},
				Kinds: []string{"function_declaration", "arrow_function"},
				Tags:  []string{"async", "style"},
			},
		},
		BugPatterns: []BugPattern{
			{
				ID:       "ts-object-access",
				Summary:  "Always narrow or use optional chaining before accessing object properties",
				Body:     "Accessing a property on null/undefined throws TypeError at runtime. Use optional chaining (?.) and nullish coalescing (??) to handle missing values safely: const name = user?.profile?.name ?? 'Anonymous'",
				Langs:    []string{"typescript", "javascript"},
				Kinds:    []string{"property_access_expression", "element_access_expression"},
				Severity: "error",
				Fix:      "Use user?.profile?.name ?? defaultValue or validate before access",
				CWE:      "CWE-476",
			},
			{
				ID:       "ts-type-assertion",
				Summary:  "Avoid non-null assertions (!) — use proper narrowing instead",
				Body:     "The ! operator (non-null assertion) tells TypeScript to trust you without verification. It bypasses strictNullChecks and can cause TypeError at runtime. Use explicit checks or optional chaining instead.",
				Langs:    []string{"typescript"},
				Kinds:    []string{"as_expression", "non_null_expression"},
				Severity: "warning",
				Fix:      "Use if (val !== undefined) or optional chaining (?.) instead of val!",
			},
			{
				ID:       "ts-implicit-any",
				Summary:  "Implicit any from noImplicitAny — annotate or use unknown",
				Body:     "Parameter or variable inferred as implicit any. This disables type checking for that symbol. Either annotate explicitly with a type or use : unknown if the type is truly indeterminate.",
				Langs:    []string{"typescript"},
				Kinds:    []string{"parameter", "variable_declaration"},
				Severity: "warning",
				CWE:      "CWE-710", // Improperly specified programming language conventions
			},
			{
				ID:       "js-array-mutation",
				Summary:  "Avoid mutating shared arrays — use spread or Array.from",
				Body:     "Mutating function arguments (e.g., arr.push(...)) modifies the caller's state, causing hard-to-trace bugs. Return a new array instead or use [...arr, newItem] for immutable appends.",
				Langs:    []string{"typescript", "javascript"},
				Kinds:    []string{"call_expression", "update_expression"},
				Severity: "warning",
			},
			{
				ID:       "ts-shallow-equal",
				Summary:  "Comparing objects with === compares references, not values",
				Body:     "Two objects with identical content are !== unless they are the same reference in memory. Use a deep equality function (like lodash isEqual) or compare specific fields for value equality.",
				Langs:    []string{"typescript", "javascript"},
				Kinds:    []string{"binary_expression"},
				Severity: "warning",
			},
			{
				ID:       "ts-promises",
				Summary:  "Unhandled Promise rejections — always add catch or use await in try/catch",
				Body:     "A Promise rejection without a .catch handler throws synchronously in Node 15+ and causes an unhandled rejection event. Always chain .catch or use try { await x } catch { }.",
				Langs:    []string{"typescript", "javascript"},
				Kinds:    []string{"await_expression", "call_expression"},
				Severity: "error",
				CWE:      "CWE-755",
			},
		},
		SecurityRules: []SecurityRule{
			{
				ID:       "ts-xss-innerHTML",
				Summary:  "Never set innerHTML with unsanitized user input — use textContent",
				Body:     "innerHTML with user-controlled content is XSS. Use element.textContent = userValue for plain text, or a sanitizer library (DOMPurify) if HTML is genuinely required and intentionally crafted by a trusted source.",
				Langs:    []string{"typescript", "javascript"},
				Kinds:    []string{"assignment", "call_expression"},
				CWE:      "CWE-79",
				OWASP:    "A03:2021",
				Severity: "critical",
			},
			{
				ID:       "ts-prototype-pollution",
				Summary:  "Check for __proto__, constructor, and prototype in JSON.parse input",
				Body:     "Merging untrusted JSON into objects allows attacker-controlled prototype pollution. Use Object.freeze, Map instead of plain objects for key-value storage, or a sanitizer that blocks prototype keys. Validate all user JSON input before merging.",
				Langs:    []string{"typescript", "javascript"},
				Kinds:    []string{"call_expression", "binary_expression"},
				CWE:      "CWE-1321",
				OWASP:    "A03:2021",
				Severity: "high",
			},
			{
				ID:       "ts-eval",
				Summary:  "Avoid eval and new Function — they execute arbitrary code",
				Body:     "eval and new Function(String) execute arbitrary JavaScript. User-controlled input in either is a code injection vulnerability. Use JSON.parse for data, or sandboxed scripting (e.g. isolated VM) for untrusted expressions.",
				Langs:    []string{"typescript", "javascript"},
				Kinds:    []string{"call_expression"},
				CWE:      "CWE-95",
				Severity: "critical",
			},
			{
				ID:       "ts-url-redirection",
				Summary:  "Validate and safelist redirect URLs to prevent open redirect attacks",
				Body:     "Passing user input to location.href or window.location without validation allows open redirect attacks. Safelist allowed domains or paths, never accept full URLs from untrusted sources. Validate with URL constructor and check the origin.",
				Langs:    []string{"typescript", "javascript"},
				Kinds:    []string{"assignment", "call_expression"},
				CWE:      "CWE-601",
				OWASP:    "A01:2021",
				Severity: "high",
			},
			{
				ID:       "ts-hardcoded-secret",
				Summary:  "Do not embed secrets, API keys, or tokens in TypeScript source",
				Body:     "Secrets in source code are visible to anyone with the bundle. Use environment variables (process.env.SECRET), a secrets manager, or a .env file excluded from source control.",
				Langs:    []string{"typescript", "javascript"},
				Kinds:    []string{"variable_declaration", "property"},
				CWE:      "CWE-798",
				Severity: "critical",
			},
			{
				ID:       "ts-sql-injection",
				Summary:  "Use parameterized queries — never concatenate user input into SQL",
				Body:     "Template literal or string concatenation into SQL is SQL injection. Use the database driver's parameterized queries: db.query('SELECT * FROM users WHERE id = $1', [userId]) in node-postgres, or an ORM that generates parameterized queries.",
				Langs:    []string{"typescript", "javascript"},
				Kinds:    []string{"call_expression", "template_literal"},
				CWE:      "CWE-89",
				OWASP:    "A03:2021",
				Severity: "critical",
			},
		},
		Idioms: []Idiom{
			{ID: "tsPascalCase", Lang: "typescript", Rule: "Use PascalCase for types, interfaces, enums, and React components",
				Detail: "TypeScript convention: interfaces and types are nouns (UserProfile), not prefixed with I. React components are PascalCase.",
				Kinds: []string{"interface_declaration", "type_alias", "function_declaration", "class_declaration"}},
			{ID: "tscamelCase", Lang: "typescript", Rule: "Use camelCase for variables, functions, and methods",
				Detail: "Variables and functions use camelCase. Constants that are truly immutable are SCREAMING_SNAKE_CASE.",
				Kinds: []string{"variable_declaration", "function_declaration", "method_declaration"}},
			{ID: "ts-barrel-export", Lang: "typescript", Rule: "Use barrel files (index.ts) to re-export from a module",
				Detail: "A barrel (index.ts that re-exports from sibling files) simplifies imports and enables tree-shaking: import { UserCard } from 'components/User' vs import { UserCard } from 'components/User/Card'.",
				Kinds: []string{"export_statement"}},
			{ID: "ts-exhaustive-switch", Lang: "typescript", Rule: "Use switch with exhaustive case checking on union types",
				Detail: "Add a default case that assigns to never after all union members are handled. If default is unreachable, TypeScript will error if a new union member is added without handling it.",
				Kinds: []string{"switch_statement"}},
		},
	}
}
